s=str(input('dati sirul '))
a=s.count('A')
b=s.replace('A','*')
c=s.replace('B','')
d=s.count('MA')
e=s.replace('MA','TA')
f=s.replace('TO','')
print ('a) A apare de:',a,'ori')
print ('b) Numarul de apartitii A  * :',b)
print ('c) Sirul fara B:',c)
print ('d) Numarul de aparitii MA:',d,'ori')
print ('e) Sirul MA TA:',e)
print ('f) Sirul fara TO:',f)
print ('g) Sirul invers:',s[::-1])
